export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAILURE = "ADMIN_USERS_FAILURE";

export const ADMIN_USERS_DELETE_REQUEST = "ADMIN_USERS_DELETE_REQUEST";
export const ADMIN_USERS_DELETE_SUCCESS = "ADMIN_USERS_DELETE_SUCCESS";
export const ADMIN_USERS_DELETE_FAILURE = "ADMIN_USERS_DELETE_FAILURE";
